# Generated by Django 2.2.5 on 2019-09-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=45, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=45, verbose_name='Address line 2')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(blank=True, max_length=40, verbose_name='State/Province')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'unique_together': {('address_line1', 'address_line2', 'postal_code', 'city', 'state_province', 'country')},
            },
        ),
    ]
