# Generated by Django 2.2.5 on 2019-09-25 18:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user_photos'),
        ),
    ]
