# Generated by Django 2.2.5 on 2019-09-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
